const $=s=>document.querySelector(s);const api=()=>$('#api').value.replace(/\/$/,'');
const reviewItems=new Map();
async function request(path,options={}){const r=await fetch(api()+path,{headers:{'Content-Type':'application/json'},...options});const j=await r.json();if(!r.ok||j.code!==200)throw new Error(j.message||'请求失败');return j.data}
function page(name){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));$('#'+(name==='users'?'users-page':name)).classList.add('active');document.querySelector(`[data-page="${name}"]`).classList.add('active');$('#title').textContent=({dashboard:'运营概览',reviews:'内容审核',keywords:'风险关键词','record-types':'成长打卡类型',learning:'成长学习内容',settings:'系统设置',users:'账号管理'})[name];if(name==='reviews')loadReviews();if(name==='keywords')loadKeywords();if(name==='record-types')loadRecordTypes();if(name==='learning')loadLearningContents();if(name==='settings')loadSettings()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>page(b.dataset.page));
async function loadStats(){try{const d=await request('/admin/stats');[['users','users'],['contents','contents'],['posts','posts'],['listings','secondHandListings']].forEach(([id,key])=>$('#'+id).textContent=d[key])}catch(e){alert('无法连接后端：'+e.message)}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function itemCard(type,item){reviewItems.set(`${type}:${item.id}`,item);const text=item.title||item.description||item.body||'';const label={contents:'知识投稿',posts:'社区帖子',comments:'社区评论','second-hand':'二手信息'}[type];return `<article class="review"><div class="row"><strong>${escapeHtml(text).slice(0,72)}</strong><span class="badge">${item.riskLevel||'人工审核'}</span></div><div class="meta">${label} · ID ${item.id} · 当前状态：${item.status}</div><div class="actions"><button onclick="showDetail('${type}',${item.id})">查看内容</button><button onclick="review('${type}',${item.id},'PUBLISHED')">通过</button><button class="reject" onclick="review('${type}',${item.id},'REJECTED')">驳回</button><button onclick="review('${type}',${item.id},'OFFLINE')">下架</button></div></article>`}
async function loadReviews(){try{const d=await request('/admin/reviews?status='+$('#review-status').value);reviewItems.clear();const rows=[...d.contents.map(x=>itemCard('contents',x)),...d.posts.map(x=>itemCard('posts',x)),...d.comments.map(x=>itemCard('comments',x)),...d.secondHand.map(x=>itemCard('second-hand',x))];$('#review-list').innerHTML=rows.length?rows.join(''):'<p class="muted">该状态下没有记录。</p>'}catch(e){alert(e.message)}}
function detailRow(label,value){if(value===undefined||value===null||value==='')return '';return `<div><dt>${escapeHtml(label)}</dt><dd>${escapeHtml(value)}</dd></div>`}
function linkRow(label,url){if(!url)return '';const safe=escapeHtml(url);return `<div><dt>${escapeHtml(label)}</dt><dd><a class="detail-link" href="${safe}" target="_blank" rel="noopener">${safe}</a></dd></div>`}
function showDetail(type,id){const item=reviewItems.get(`${type}:${id}`);if(!item)return;const labels={contents:'知识投稿详情',posts:'社区帖子详情',comments:'社区评论详情','second-hand':'二手信息详情'};let html=detailRow('内容 ID',item.id)+detailRow('风险等级',item.riskLevel)+detailRow('当前状态',item.status)+detailRow('用户 ID',item.userId);if(type==='contents')html+=detailRow('标题',item.title)+detailRow('完整摘要',item.summary)+linkRow('来源链接',item.sourceUrl)+detailRow('授权/许可依据',item.licenseBasis)+detailRow('审核备注',item.reviewerNote);if(type==='posts')html+=detailRow('标题',item.title)+detailRow('完整正文',item.body)+detailRow('发布方式',item.anonymous?'匿名发布':'实名发布');if(type==='comments')html+=detailRow('所属帖子 ID',item.postId)+detailRow('完整评论',item.body)+detailRow('发布方式',item.anonymous?'匿名发布':'实名发布');if(type==='second-hand')html+=detailRow('教具名称',item.title)+detailRow('完整说明',item.description)+detailRow('置换需求',item.exchangeNeed)+detailRow('公益边界','仅提供线下自主沟通，平台不参与定价、支付、担保、物流和售后。');$('#detail-title').textContent=labels[type];$('#detail-body').innerHTML=html;$('#detail-modal').classList.add('open');$('#detail-modal').setAttribute('aria-hidden','false')}
function closeDetail(){$('#detail-modal').classList.remove('open');$('#detail-modal').setAttribute('aria-hidden','true')}
window.showDetail=showDetail;window.closeDetail=closeDetail;
async function review(type,id,action){try{await request(`/admin/${type}/${id}/review`,{method:'POST',body:JSON.stringify({action,note:'管理端审核'})});loadReviews();loadStats()}catch(e){alert(e.message)}}
$('#user-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await request(`/admin/users/${d.userId}/status`,{method:'POST',body:JSON.stringify({status:d.status})});alert('账号状态已更新')}catch(err){alert(err.message)}};loadStats();
function keywordCard(rule){return `<article class="review"><div class="row"><strong>${rule.keyword}</strong><span class="badge">${rule.riskLevel} · ${rule.enabled?'启用':'停用'}</span></div><div class="meta">优先级：${rule.priority} · ${rule.reviewRequired?'命中后需要人工审核':'命中后自动发布'} · ${rule.remark||'无说明'}</div><div class="actions"><button onclick="toggleKeyword(${rule.id},${!rule.enabled})">${rule.enabled?'停用':'启用'}</button><button class="reject" onclick="removeKeyword(${rule.id})">删除</button></div></article>`}
async function loadKeywords(){try{const data=await request('/admin/risk-keywords');$('#keyword-list').innerHTML=data.length?data.map(keywordCard).join(''):'<p class="muted">尚未配置关键词。</p>'}catch(e){alert(e.message)}}
async function toggleKeyword(id,enabled){try{await request(`/admin/risk-keywords/${id}/enabled`,{method:'POST',body:JSON.stringify({enabled})});loadKeywords()}catch(e){alert(e.message)}}
async function removeKeyword(id){if(!confirm('确认删除该规则？'))return;try{await request(`/admin/risk-keywords/${id}`,{method:'DELETE'});loadKeywords()}catch(e){alert(e.message)}}
$('#keyword-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await request('/admin/risk-keywords',{method:'POST',body:JSON.stringify({...d,priority:+d.priority,reviewRequired:!!d.reviewRequired,enabled:true})});e.target.reset();e.target.priority.value=100;e.target.reviewRequired.checked=true;loadKeywords()}catch(err){alert(err.message)}};
function recordTypeCard(t){return '<article class="review"><div class="row"><strong>'+escapeHtml(t.name)+'</strong><span class="badge">'+escapeHtml(t.code)+' · '+(t.enabled?'启用':'停用')+'</span></div><div class="meta">排序：'+t.sortOrder+' · '+escapeHtml(t.remark||'无说明')+'</div><div class="actions"><button onclick="toggleRecordType('+t.id+','+(!t.enabled)+')">'+(t.enabled?'停用':'启用')+'</button><button class="reject" onclick="removeRecordType('+t.id+')">删除</button></div></article>'}
async function loadRecordTypes(){try{const data=await request('/admin/record-types');$('#record-type-list').innerHTML=data.length?data.map(recordTypeCard).join(''):'<p class="muted">尚未配置成长打卡类型。</p>'}catch(e){alert(e.message)}}
async function toggleRecordType(id,enabled){try{await request('/admin/record-types/'+id+'/enabled',{method:'POST',body:JSON.stringify({enabled})});loadRecordTypes()}catch(e){alert(e.message)}}
async function removeRecordType(id){if(!confirm('确认删除该类型？删除后 APP 不再显示该类型。'))return;try{await request('/admin/record-types/'+id,{method:'DELETE'});loadRecordTypes()}catch(e){alert(e.message)}}
$('#record-type-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await request('/admin/record-types',{method:'POST',body:JSON.stringify({...d,sortOrder:+d.sortOrder,enabled:true})});e.target.reset();e.target.sortOrder.value=100;loadRecordTypes()}catch(err){alert(err.message)}};
async function loadSettings(){try{const data=await request('/admin/system-settings'),form=$('#settings-form'),row=$('#settings .row'),refresh=row.querySelector('button[onclick]');let save=$('#settings-save')||form.querySelector('button'),actions=$('#settings-actions');if(!actions){actions=document.createElement('div');actions.id='settings-actions';actions.style.cssText='display:flex;gap:8px;align-items:center';row.append(actions)}if(save){save.id='settings-save';save.type='submit';save.setAttribute('form','settings-form');actions.append(save,refresh)}if(!$('#community-permissions'))form.insertAdjacentHTML('beforeend','<fieldset id="community-permissions"><legend>社区用户操作权限</legend><label><input id="allow-comment-edit" type="checkbox"/> 允许评论作者编辑自己的评论</label><label><input id="allow-comment-delete" type="checkbox"/> 允许评论作者删除自己的评论</label><label><input id="allow-post-delete" type="checkbox"/> 允许帖子作者删除自己的帖子</label></fieldset><fieldset id="training-category-settings"><legend>每日训练参数</legend><label>训练目标分类（逗号分隔）<input id="training-categories" type="text" placeholder="沟通表达,生活自理"/></label></fieldset>');$('#community-max-images').value=data.communityMaxImages;$('#training-categories').value=(data.trainingCategories||[]).join(',');$('#allow-comment-edit').checked=!!data.allowCommentEdit;$('#allow-comment-delete').checked=!!data.allowCommentDelete;$('#allow-post-delete').checked=!!data.allowPostDelete}catch(e){alert(e.message)}}
$('#settings-form').onsubmit=async e=>{e.preventDefault();const maxImages=+$('#community-max-images').value;try{await request('/admin/system-settings/community-max-images',{method:'POST',body:JSON.stringify({maxImages})});await request('/admin/system-settings/community-permissions',{method:'POST',body:JSON.stringify({allowCommentEdit:$('#allow-comment-edit').checked,allowCommentDelete:$('#allow-comment-delete').checked,allowPostDelete:$('#allow-post-delete').checked})});await request('/admin/system-settings/training-categories',{method:'POST',body:JSON.stringify({categories:$('#training-categories').value})});alert('系统设置已保存')}catch(err){alert(err.message)}};
let learningItems=[];function learningCard(item){return `<article class="review"><div class="row"><strong>${escapeHtml(item.icon||'📖')} ${escapeHtml(item.title)}</strong><span class="badge">${item.published?'已发布':'已下线'}</span></div><div class="meta">${escapeHtml(item.category)} · ${escapeHtml(item.readingTime||'3 分钟')} · 排序 ${item.sortOrder}</div><div class="actions"><button onclick="editLearning(${item.id})">编辑</button><button onclick="toggleLearning(${item.id},${!item.published})">${item.published?'下线':'发布'}</button><button class="reject" onclick="removeLearning(${item.id})">删除</button></div></article>`}async function loadLearningContents(){try{learningItems=await request('/admin/learning-contents');$('#learning-list').innerHTML=learningItems.length?learningItems.map(learningCard).join(''):'<p class="muted">尚未配置内容，可先新增一篇家庭方法卡。</p>'}catch(e){alert(e.message)}}function resetLearningForm(){const f=$('#learning-form');f.reset();f.elements.id.value='';f.icon.value='📖';f.readingTime.value='3 分钟';f.sortOrder.value=100;f.published.checked=true}function editLearning(id){const item=learningItems.find(x=>x.id===id),f=$('#learning-form');if(!item)return;Object.keys(item).forEach(key=>{if(f.elements[key])f.elements[key].value=item[key]??''});f.published.checked=item.published;document.querySelector("#learning-modal-title").textContent="编辑成长学习内容";document.querySelector("#learning-modal").classList.add("open");document.querySelector("#learning-modal").setAttribute("aria-hidden","false")}async function toggleLearning(id,published){try{await request('/admin/learning-contents/'+id+'/published',{method:'POST',body:JSON.stringify({published})});loadLearningContents()}catch(e){alert(e.message)}}async function removeLearning(id){if(!confirm('确认删除该学习内容？'))return;try{await request('/admin/learning-contents/'+id,{method:'DELETE'});loadLearningContents()}catch(e){alert(e.message)}}$('#learning-form').onsubmit=async e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));d.sortOrder=+d.sortOrder;d.published=f.published.checked;try{await request(d.id?'/admin/learning-contents/'+d.id:'/admin/learning-contents',{method:d.id?'PUT':'POST',body:JSON.stringify(d)});resetLearningForm();closeLearningModal();loadLearningContents()}catch(err){alert(err.message)}};window.loadLearningContents=loadLearningContents;window.editLearning=editLearning;window.toggleLearning=toggleLearning;window.removeLearning=removeLearning;window.resetLearningForm=resetLearningForm;
