const learningForm = document.querySelector('#learning-form');
learningForm.insertAdjacentHTML('afterend', '<aside id="learning-preview" class="learning-preview"></aside>');
const previewEscape = value => String(value || '').replace(/[&<>"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[char]));
function renderLearningPreview() { const value = name => learningForm.elements[name]?.value || ''; const steps = value('steps').split(/\n|\|/).map(item => item.trim()).filter(Boolean); const edit = (field, text, cls = '') => `<span class="preview-edit ${cls}" contenteditable="true" data-field="${field}">${previewEscape(text)}</span>`; document.querySelector('#learning-preview').innerHTML = `<p class="preview-kicker">APP 展示预览 · 可直接点击文字修改</p><div class="preview-phone"><div class="preview-hero"><span>星宝成长小课堂</span><b>把方法变成<br/>今天能做的小一步</b></div><div class="preview-card"><i>${edit('icon', value('icon') || '📖')}</i><div><em>${edit('category', value('category') || '分类')} · ${edit('readingTime', value('readingTime') || '3 分钟')}</em><strong>${edit('title', value('title') || '方法标题')}</strong><small>${edit('intro', value('intro') || '这里展示方法简介，帮助家长快速了解适用场景。')}</small></div><b>›</b></div><div class="preview-detail"><span>${edit('icon', value('icon') || '📖')} ${edit('category', value('category') || '分类')}</span><h3>${edit('title', value('title') || '方法标题')}</h3><ol>${(steps.length ? steps : ['操作步骤会显示在这里']).map(step => `<li class="preview-step" contenteditable="true">${previewEscape(step)}</li>`).join('')}</ol><p class="preview-tip">小提示：${edit('tip', value('tip') || '点击这里填写给家长的小提示')}</p></div></div>`; }
learningForm.addEventListener('input', renderLearningPreview);
document.querySelector('#learning-preview').addEventListener('input', event => { const field = event.target.dataset.field; if (field && learningForm.elements[field]) learningForm.elements[field].value = event.target.textContent.trim(); if (event.target.classList.contains('preview-step')) learningForm.elements.steps.value = [...document.querySelectorAll('.preview-step')].map(item => item.textContent.trim()).filter(Boolean).join('\n'); });
document.querySelector('#learning-preview').addEventListener('focusout', event => { if (event.target.closest('.preview-edit,.preview-step')) renderLearningPreview(); });
window.openLearningModal = () => { resetLearningForm(); document.querySelector('#learning-modal-title').textContent = '新增成长学习内容'; document.querySelector('#learning-modal').classList.add('open'); document.querySelector('#learning-modal').setAttribute('aria-hidden', 'false'); renderLearningPreview(); };
window.closeLearningModal = () => { document.querySelector('#learning-modal').classList.remove('open'); document.querySelector('#learning-modal').setAttribute('aria-hidden', 'true'); };
async function loadLearningCategories(selected = '') { try { const data = await request('/settings/learning-categories'); const select = learningForm.elements.category; select.innerHTML = data.categories.map(item => `<option value="${previewEscape(item)}">${previewEscape(item)}</option>`).join(''); select.value = data.categories.includes(selected) ? selected : data.categories[0]; } catch (error) { learningForm.elements.category.innerHTML = '<option>通用方法</option>'; } }
const openNewLearningModal = window.openLearningModal;
window.openLearningModal = async () => { openNewLearningModal(); await loadLearningCategories(); renderLearningPreview(); };
const editExistingLearning = window.editLearning;
window.editLearning = async id => { const item = window.learningItems?.find?.(entry => entry.id === id); await loadLearningCategories(item?.category || ''); editExistingLearning(id); renderLearningPreview(); };
const originalEditLearning = window.editLearning;
window.editLearning = id => { originalEditLearning(id); renderLearningPreview(); };
document.querySelector('#learning-modal').addEventListener('click', event => { if (event.target.id === 'learning-modal') closeLearningModal(); });
document.head.insertAdjacentHTML('beforeend', `<style>.learning-modal-card{width:min(1030px,100%);display:grid;grid-template-columns:minmax(0,1fr) 320px;gap:20px;background:linear-gradient(135deg,#fff,#fff9fa)}.learning-modal-card>.row{grid-column:1/-1;margin:0;padding-bottom:15px;border-bottom:1px solid #f0e2e6}.learning-modal-card>.learning-form{grid-column:1;margin:0;padding:18px;border:1px solid #f0e4e8;border-radius:15px;background:#fff}.learning-preview{grid-column:2;padding:16px;border-radius:16px;background:#f8eef1}.preview-kicker{margin:0 0 9px;color:#b46d81;font-size:12px;font-weight:800;letter-spacing:.06em}.preview-phone{overflow:hidden;border:7px solid #3c3640;border-radius:24px;background:#fff;box-shadow:0 10px 24px #8c536333}.preview-hero{padding:16px;color:#fff;background:linear-gradient(135deg,#ff88a2,#f6ae7f)}.preview-hero span{display:block;font-size:10px;opacity:.9}.preview-hero b{display:block;margin-top:4px;font-size:17px;line-height:1.3}.preview-card{display:grid;grid-template-columns:33px 1fr 12px;gap:7px;align-items:center;margin:10px;padding:10px;border:1px solid #f0e0e4;border-radius:12px}.preview-card i{display:grid;place-items:center;width:33px;height:33px;border-radius:10px;background:#fff0f3;font-style:normal}.preview-card div{display:grid;gap:2px;min-width:0}.preview-card em{color:#bd7a8b;font-size:9px;font-style:normal}.preview-card strong{font-size:12px}.preview-card small{overflow:hidden;color:#8b7b80;font-size:10px;text-overflow:ellipsis;white-space:nowrap}.preview-card>b{color:#e2889d;font-size:19px;font-weight:400}.preview-detail{margin:0 10px 12px;padding:10px;border-radius:11px;background:#fff7f8;color:#725e64}.preview-detail>span{color:#bd7a8b;font-size:9px}.preview-detail h3{margin:5px 0;font-size:13px}.preview-detail ol{margin:0;padding-left:16px;font-size:10px;line-height:1.6}.preview-detail p{margin:7px 0 0;color:#946f57;font-size:10px;line-height:1.4}.preview-edit,.preview-step{outline:1px dashed transparent;border-radius:3px;cursor:text}.preview-edit:hover,.preview-step:hover,.preview-edit:focus,.preview-step:focus{outline-color:#ef9caf;background:#fff1f4}.preview-card small .preview-edit{display:block;white-space:normal}.preview-tip{min-height:16px}@media(max-width:850px){.learning-modal-card{display:block}.learning-modal-card>.row{margin-bottom:16px}.learning-preview{display:none}}</style>`);
document.head.insertAdjacentHTML('beforeend', `<style>.learning-modal-card>.learning-form .form-grid{grid-template-columns:minmax(0,1fr) 96px!important;gap:15px!important}.learning-modal-card>.learning-form .form-grid label{padding:10px 11px;border:1px solid #eef0f4;border-radius:11px;background:#fafcff}.learning-modal-card>.learning-form .form-grid label:focus-within{border-color:#ef9db0;background:#fff9fa;box-shadow:0 0 0 3px #fff0f3}.learning-modal-card>.learning-form .form-grid label.wide{grid-column:1/-1}.learning-modal-card>.learning-form .form-grid input,.learning-modal-card>.learning-form .form-grid select,.learning-modal-card>.learning-form .form-grid textarea{margin:2px 0 0;border:0;border-radius:0;border-bottom:1px solid #d9e0eb;padding:7px 1px;background:transparent;outline:0}.learning-modal-card>.learning-form .form-grid textarea{min-height:68px;border:1px solid #dfe5ee;border-radius:8px;padding:8px;background:#fff}.learning-modal-card>.learning-form .form-grid label:nth-child(3){grid-column:1/-1}.learning-modal-card>.learning-form .modal-actions{padding-top:6px;border-top:1px solid #f0e8ea}@media(max-width:850px){.learning-modal-card>.learning-form .form-grid{grid-template-columns:minmax(0,1fr) 82px!important}}</style>`);
