package cn.xingbao.controller;
import cn.xingbao.common.ApiResponse; import cn.xingbao.domain.*; import cn.xingbao.repo.*; import cn.xingbao.service.RiskService; import org.springframework.data.domain.Page; import org.springframework.data.domain.PageRequest; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.io.IOException; import java.nio.file.Files; import java.nio.file.Path; import java.util.*;
@RestController @RequestMapping("/api/v1/community/posts") public class CommunityController {
 private final PostRepository posts; private final CommentRepository comments; private final ReactionRepository reactions; private final UserRepository users; private final SystemSettingController settings; private final RiskService risk; public CommunityController(PostRepository p,CommentRepository c,ReactionRepository r,UserRepository u,SystemSettingController settings, RiskService risk){posts=p;comments=c;reactions=r;users=u;this.settings=settings;this.risk=risk;}
 @GetMapping public ApiResponse<List<CommunityPost>> list(){return ApiResponse.ok(posts.findByStatusAndDeletedFalseOrderByCreatedAtDesc("PUBLISHED"));}
 @GetMapping("/page") public ApiResponse<Map<String,Object>> page(@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="5") int size){int safePage=Math.max(0,page),safeSize=Math.min(20,Math.max(1,size));Page<CommunityPost> result=posts.findByStatusAndDeletedFalseOrderByCreatedAtDesc("PUBLISHED", PageRequest.of(safePage,safeSize));return ApiResponse.ok(Map.of("items",result.getContent(),"hasMore",result.hasNext(),"nextPage",safePage+1));}
 @GetMapping("/liked") public ApiResponse<List<Long>> liked(@RequestParam Long userId){return ApiResponse.ok(reactions.findByUserIdAndTypeAndDeletedFalse(userId,"LIKE").stream().map(CommunityReaction::getPostId).toList());}
 @PostMapping public ApiResponse<CommunityPost> create(@RequestBody CommunityPost p){validateImages(p.getImageUrls());String text=p.getTitle()+p.getBody();p.setRiskLevel(risk.evaluate(text));p.setStatus(risk.initialStatus(text));return ApiResponse.ok(posts.save(p));}
 @GetMapping("/{id}") public ApiResponse<Map<String,Object>> detail(@PathVariable Long id,@RequestParam(required=false) Long viewerId,@RequestParam(defaultValue="0") int commentPage,@RequestParam(defaultValue="3") int commentSize){CommunityPost p=posts.findById(id).orElseThrow(()->new IllegalArgumentException("帖子不存在"));List<CommunityComment> published=comments.findByPostIdAndStatusAndDeletedFalseOrderByCreatedAtAsc(id,"PUBLISHED");List<CommunityComment> visible=comments.findByPostIdAndDeletedFalseOrderByCreatedAtAsc(id).stream().filter(c->"PUBLISHED".equals(c.getStatus())||Objects.equals(c.getUserId(),viewerId)).toList();int safePage=Math.max(0,commentPage),safeSize=Math.min(20,Math.max(1,commentSize)),from=Math.min(safePage*safeSize,visible.size()),to=Math.min(from+safeSize,visible.size());List<CommunityComment> pageComments=visible.subList(from,to);Map<Long,String> commentAuthors=new HashMap<>();for(CommunityComment c:pageComments)commentAuthors.put(c.getId(),c.isAnonymous()&&!Objects.equals(c.getUserId(),viewerId)?"匿名家长":authorName(c.getUserId()));return ApiResponse.ok(Map.of("post",p,"authorName",p.isAnonymous()&&!Objects.equals(p.getUserId(),viewerId)?"匿名家长":authorName(p.getUserId()),"comments",pageComments,"publicCommentCount",published.size(),"hasMoreComments",to<visible.size(),"nextCommentPage",safePage+1,"commentAuthors",commentAuthors,"likes",reactions.countByPostIdAndTypeAndDeletedFalse(id,"LIKE"),"favorites",reactions.countByPostIdAndTypeAndDeletedFalse(id,"FAVORITE")));}
 @PostMapping("/{id}/comments") public ApiResponse<CommunityComment> comment(@PathVariable Long id,@RequestBody CommunityComment c){if(!posts.existsById(id))throw new IllegalArgumentException("帖子不存在");c.setPostId(id);c.setRiskLevel(risk.evaluate(c.getBody()));c.setStatus(risk.initialStatus(c.getBody()));return ApiResponse.ok(comments.save(c));}
 @PutMapping("/{postId}/comments/{commentId}") public ApiResponse<CommunityComment> updateComment(@PathVariable Long postId,@PathVariable Long commentId,@RequestParam Long userId,@RequestBody CommunityComment input){if(!settings.allowCommentEdit())throw new IllegalArgumentException("管理员未开启评论编辑权限");CommunityComment c=comments.findById(commentId).orElseThrow(()->new IllegalArgumentException("评论不存在"));if(!Objects.equals(c.getPostId(),postId))throw new IllegalArgumentException("评论与帖子不匹配");if(!Objects.equals(c.getUserId(),userId))throw new IllegalArgumentException("只有评论发布者可以修改");String body=input.getBody()==null?"":input.getBody().trim();if(body.isBlank())throw new IllegalArgumentException("评论内容不能为空");c.setBody(body);c.setRiskLevel(risk.evaluate(body));c.setStatus(risk.initialStatus(body));return ApiResponse.ok(comments.save(c));}
 @DeleteMapping("/{postId}/comments/{commentId}") public ApiResponse<Void> deleteComment(@PathVariable Long postId,@PathVariable Long commentId,@RequestParam Long userId){if(!settings.allowCommentDelete())throw new IllegalArgumentException("管理员未开启评论删除权限");CommunityComment c=comments.findById(commentId).orElseThrow(()->new IllegalArgumentException("评论不存在"));if(!Objects.equals(c.getPostId(),postId))throw new IllegalArgumentException("评论与帖子不匹配");if(!Objects.equals(c.getUserId(),userId))throw new IllegalArgumentException("只有评论发布者可以删除");comments.delete(c);return ApiResponse.ok(null);}
 @PostMapping("/{id}/reactions/{type}") public ApiResponse<Map<String,Object>> react(@PathVariable Long id,@PathVariable String type,@RequestParam Long userId){if(!List.of("LIKE","FAVORITE").contains(type))throw new IllegalArgumentException("互动类型不合法");Optional<CommunityReaction> existing=reactions.findByPostIdAndUserIdAndTypeAndDeletedFalse(id,userId,type);boolean active;if(existing.isPresent()){CommunityReaction r=existing.get();r.setDeleted(true);reactions.save(r);active=false;}else{CommunityReaction r=new CommunityReaction();r.setPostId(id);r.setUserId(userId);r.setType(type);reactions.save(r);active=true;}return ApiResponse.ok(Map.of("active",active,"likeCount",reactions.countByPostIdAndTypeAndDeletedFalse(id,type)));}
 @DeleteMapping("/{id}") @Transactional public ApiResponse<Void> remove(@PathVariable Long id,@RequestParam Long userId){if(!settings.allowPostDelete())throw new IllegalArgumentException("管理员未开启帖子删除权限");CommunityPost p=posts.findById(id).orElseThrow(()->new IllegalArgumentException("帖子不存在"));if(!Objects.equals(p.getUserId(),userId))throw new IllegalArgumentException("只有发布者可以删除该帖子");deletePostImages(p.getImageUrls());comments.deleteAll(comments.findByPostId(id));reactions.deleteAll(reactions.findByPostId(id));posts.delete(p);return ApiResponse.ok(null);}
 private String authorName(Long userId){return users.findById(userId).filter(u->!u.isDeleted()).map(UserAccount::getNickname).filter(name->name!=null&&!name.isBlank()).orElse("星宝家长");}
 private void validateImages(String imageUrls){if(imageUrls==null||imageUrls.isBlank())return;List<String> urls=Arrays.stream(imageUrls.split(",")).filter(s->!s.isBlank()).toList();if(urls.size()>settings.getMaxImages())throw new IllegalArgumentException("社区帖子最多上传 "+settings.getMaxImages()+" 张图片");if(urls.stream().anyMatch(url->!url.matches("/uploads/[A-Za-z0-9-]+\\.(jpg|jpeg|png)")))throw new IllegalArgumentException("图片地址不合法");}
 private void deletePostImages(String imageUrls){if(imageUrls==null||imageUrls.isBlank())return;for(String url:imageUrls.split(",")){String filename=url.replaceFirst("^/uploads/","");if(!filename.matches("[A-Za-z0-9-]+\\.(jpg|jpeg|png)"))continue;try{Files.deleteIfExists(Path.of("uploads",filename));}catch(IOException e){throw new IllegalStateException("关联图片删除失败，请稍后重试");}}}
}
