package cn.xingbao.controller;
import cn.xingbao.common.ApiResponse;import cn.xingbao.domain.*;import cn.xingbao.repo.*;import org.springframework.web.bind.annotation.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;
@RestController @RequestMapping("/api/v1/home-training") public class HomeTrainingController{
 private final TrainingTaskRepository tasks;private final TrainingLogRepository logs;private final VisualCueRepository cues;
 public HomeTrainingController(TrainingTaskRepository tasks,TrainingLogRepository logs,VisualCueRepository cues){this.tasks=tasks;this.logs=logs;this.cues=cues;}
 @GetMapping("/tasks") public ApiResponse<List<TrainingTask>> tasks(@RequestParam Long childId){return ApiResponse.ok(tasks.findByChildIdAndDeletedFalseOrderByCreatedAtDesc(childId).stream().filter(TrainingTask::isEnabled).toList());}
 @PostMapping("/tasks") public ApiResponse<TrainingTask> createTask(@RequestBody TrainingTask task){if(task.getChildId()==null||task.getTitle()==null||task.getTitle().isBlank())throw new IllegalArgumentException("请选择档案并填写任务名称");task.setDailyTarget(Optional.ofNullable(task.getDailyTarget()).orElse(BigDecimal.ONE));if(!List.of("HOUR","DAY").contains(task.getDailyUnit()))task.setDailyUnit("DAY");return ApiResponse.ok(tasks.save(task));}
 @PostMapping("/tasks/{id}/logs") public ApiResponse<TrainingLog> record(@PathVariable Long id,@RequestBody TrainingLog input){if(!List.of("DONE","ASSISTED","MISSED").contains(input.getResult()))throw new IllegalArgumentException("记录结果不合法");tasks.findById(id).filter(x->!x.isDeleted()).orElseThrow(()->new IllegalArgumentException("任务不存在"));LocalDate today=LocalDate.now();TrainingLog log=logs.findFirstByTaskIdAndRecordDateAndDeletedFalseOrderByCreatedAtDesc(id,today).orElseGet(TrainingLog::new);log.setTaskId(id);log.setRecordDate(today);log.setResult(input.getResult());return ApiResponse.ok(logs.save(log));}
 @PostMapping("/tasks/{id}/end") public ApiResponse<TrainingTask> endTask(@PathVariable Long id){TrainingTask task=tasks.findById(id).filter(x->!x.isDeleted()).orElseThrow(()->new IllegalArgumentException("任务不存在"));task.setEnabled(false);return ApiResponse.ok(tasks.save(task));}
 @GetMapping("/trend") public ApiResponse<Map<String,Object>> trend(@RequestParam Long childId){List<TrainingTask> list=tasks.findByChildIdAndDeletedFalseOrderByCreatedAtDesc(childId);if(list.isEmpty())return ApiResponse.ok(Map.of("days",List.of(),"total",0,"done",0));List<Long> ids=list.stream().map(TrainingTask::getId).toList();LocalDate end=LocalDate.now(),start=end.minusDays(6);List<TrainingLog> records=effectiveLogs(logs.findByTaskIdInAndRecordDateBetweenAndDeletedFalse(ids,start,end));List<Map<String,Object>> days=new ArrayList<>();for(int i=0;i<7;i++){LocalDate day=start.plusDays(i);long total=records.stream().filter(x->x.getRecordDate().equals(day)).count(),done=records.stream().filter(x->x.getRecordDate().equals(day)&&"DONE".equals(x.getResult())).count();days.add(Map.of("date",day.toString(),"total",total,"done",done));}long done=records.stream().filter(x->"DONE".equals(x.getResult())).count();return ApiResponse.ok(Map.of("days",days,"total",records.size(),"done",done));}
 @GetMapping("/trend/day") public ApiResponse<List<Map<String,Object>>> trendDay(@RequestParam Long childId,@RequestParam LocalDate date,@RequestParam(defaultValue="true") boolean includeEnded){List<TrainingTask> list=tasks.findByChildIdAndDeletedFalseOrderByCreatedAtDesc(childId);if(!includeEnded)list=list.stream().filter(TrainingTask::isEnabled).toList();if(list.isEmpty())return ApiResponse.ok(List.of());List<Long> ids=list.stream().map(TrainingTask::getId).toList();Map<Long,TrainingLog> state=new HashMap<>();for(TrainingLog log:effectiveLogs(logs.findByTaskIdInAndRecordDateAndDeletedFalse(ids,date)))state.put(log.getTaskId(),log);List<Map<String,Object>> result=new ArrayList<>();for(TrainingTask task:list){Map<String,Object> item=new LinkedHashMap<>();item.put("id",task.getId());item.put("title",task.getTitle());item.put("category",task.getCategory());item.put("dailyTarget",task.getDailyTarget());item.put("dailyUnit",task.getDailyUnit());item.put("result",state.containsKey(task.getId())?state.get(task.getId()).getResult():"PENDING");result.add(item);}return ApiResponse.ok(result);}
 private List<TrainingLog> effectiveLogs(List<TrainingLog> source){Map<String,TrainingLog> latest=new LinkedHashMap<>();for(TrainingLog log:source){String key=log.getTaskId()+"|"+log.getRecordDate();TrainingLog old=latest.get(key);if(old==null||log.getId()>old.getId())latest.put(key,log);}return new ArrayList<>(latest.values());}
 @GetMapping("/cues") public ApiResponse<List<VisualCue>> cues(@RequestParam Long childId){return ApiResponse.ok(cues.findByChildIdAndDeletedFalseOrderByCreatedAtDesc(childId));}
 @PostMapping("/cues") public ApiResponse<VisualCue> createCue(@RequestBody VisualCue cue){if(cue.getChildId()==null||cue.getTitle()==null||cue.getTitle().isBlank())throw new IllegalArgumentException("请选择档案并填写提示语");if(cue.getColor()==null||!cue.getColor().matches("#[0-9A-Fa-f]{6}"))cue.setColor("#FFE1EB");return ApiResponse.ok(cues.save(cue));}
 @DeleteMapping("/cues/{id}") public ApiResponse<Void> deleteCue(@PathVariable Long id){VisualCue cue=cues.findById(id).filter(x->!x.isDeleted()).orElseThrow(()->new IllegalArgumentException("提示卡不存在"));cue.setDeleted(true);cues.save(cue);return ApiResponse.ok(null);}
}
